Implemented Cascadia support
rusteomics/mzcore pull request #51
Opened 2024-12-18 14:58 UTC by aukeheerdink

With this update [.ssl files](https://skyline.ms/wiki/home/software/BiblioSpec/page.view?name=BiblioSpec%20input%20and%20output%20file%20formats) are now also supported. There were a few more extra optional columns that I could also add, but I didn't see the relevance. But if you want me to add them let me know. The columns that are used by [cascadia](https://cascadia.readthedocs.io/en/latest/file_formats.html#output-format) are added.

2024-12-18 16:06 UTC, douweschulte requested changes
Maybe adding start+end-time and score-type would not hurt, mostly to show to users in the annotator though. This would mostly help with files not from cascadia, which touches on the point that this is a generic file format and that should be represented in the naming (just as is done with mzTab). To properly support this as a generic format I would argue that taking up each column that is described in the format would be good. The ones with hard to parse info could just be accepted as string. The ion mobility ones can just be floating points (the units are not part of my current unit system).

2024-12-18 16:48 UTC, aukeheerdink commented
Sure will do, what do you want me to call the generic type? ssl.rs? Or something with SpectrumSequenceList.rs, I would think ssl.rs to keep with the style of mztab?

2024-12-18 17:32 UTC, douweschulte commented
The type can be the long version I think 'SpectsumSequenceList' butthe module name (and file name) can be ssl.rs indeed.

2024-12-19 10:50 UTC, douweschulte approved these changes

2024-12-19 10:50 UTC, merged